from django.urls import path
from . import views
urlpatterns = [
path('', views.index, name= "books.index"),
path('index2/<int:val1>/', views.index2),
path('listbooks/', views.listbooks, name= "books.listbooks"),
path('<int:bookId>', views.viewbook,name="books.viewBook"),
path('searchBook/', views.searchBook,name="searchBook"),
path('findBook/', views.findBook,name="books.findBook"),
path('simpleQuery/', views.simple_query,name="books.simpleQuery"),
path('complex_query/', views.complex_query,name="books.complex_query"),
path('task1/', views.task1,name="books.task1"),
path('task2/', views.task2,name="books.task2"),
path('task3/', views.task3,name="books.task3"),
path('task4/', views.task4,name="books.task4"),
path('task5/', views.task5,name="books.task5"),
path('task7/', views.showStudentsInCity,name="books.task7"),
path('addBook', views.addBook, name="books.addBook"),
path('updateBook/<int:book_id>', views.updateBook, name="books.updateBook"),
path('deleteBook/<int:book_id>', views.deleteBook, name="books.deleteBook"),
 path('lab9_part2/listbooks', views.lab9_part2_listbooks, name='lab9_part2.listbooks'),
    path('lab9_part2/addbook', views.lab9_part2_addbook, name='lab9_part2.addbook'),
    path('lab9_part2/editbook/<int:book_id>', views.lab9_part2_editbook, name='lab9_part2.editbook'),
    path('lab9_part2/deletebook/<int:book_id>', views.lab9_part2_deletebook, name='lab9_part2.deletebook'),
 path('students/listStudents', views.listStudents, name='students.listStudents'),
    path('students/addStudent', views.addStudent, name='students.addStudent'),
    path('students/editStudent/<int:student_id>', views.editStudent, name='students.editStudent'),
    path('students/deleteStudent/<int:student_id>', views.deleteStudent, name='students.deleteStudent'),
 path('students2/listStudents', views.listStudents2, name='students2.listStudents'),
    path('students2/addStudent', views.addStudent2, name='students2.addStudent'),
    path('students2/editStudent/<int:student_id>', views.editStudent2, name='students2.editStudent'),
    path('students2/deleteStudent/<int:student_id>', views.deleteStudent2, name='students2.deleteStudent'),
     path('students_with_image/add', views.addStudentWithImage, name='students.addStudentWithImage'),
    path('students_with_image/list', views.listStudentsWithImage, name='students.listStudentsWithImage'),
]